apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
      - name: external-registry
      containers:
      - name: web
        image: dawid.azurecr.io/todo-fe-rh3:1.0
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:3001/api"