apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-backup
spec:
  template:
    spec:
      containers:
      - name: mongo-backup
        image: mongo:latest
        command:
        - /bin/sh
        - -c
        - |
          mongodump --uri="mongodb://root:password@mongo-service:27017/todos?authSource=admin" --out=/backup/$(date +%Y%m%d_%H%M%S)
        volumeMounts:
        - name: backup-volume
          mountPath: /backup
      volumes:
      - name: backup-volume
        persistentVolumeClaim:
          claimName: mongo-backup-pvc
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 