# ResourceQuota definiuje limity zasobów dla całego namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: dawid
spec:
  hard:
    # Limity zasobów obliczeniowych
    requests.cpu: "8"        # Limit CPU do 8 rdzeni
    requests.memory: 8Gi     # Limit pamięci do 8 GB
    limits.cpu: "16"         # Limit CPU do 16 rdzeni
    limits.memory: 16Gi      # Limit pamięci do 16 GB
    
    # Limity liczby obiektów
    pods: "20"               # Liczba podów
    services: "10"           # Liczba serwisów
    persistentvolumeclaims: "5"  # Liczba PVC
    
    # Limity dla load balancerów
    services.loadbalancers: "4"  # Liczba load balancerów
    
    # Limity dla NodePort
    services.nodeports: "5"      # Liczba NodePort
    
    # Limity dla sekretów i configmapów
    secrets: "20"            # Liczba sekretów
    configmaps: "20"         # Liczba configmapów
    
    # Limity dla zasobów storage
    requests.storage: "100Gi"    # Łączny limit storage 