apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduled-app
spec:
  replicas: 0  # KEDA będzie zarządzać liczbą replik
  selector:
    matchLabels:
      app: scheduled-app
  template:
    metadata:
      labels:
        app: scheduled-app
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

