apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: multi-schedule-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: scheduled-app
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
  # Dni robocze normalne godziny
  - type: cron
    metadata:
      timezone: Europe/Warsaw
      start: 0 9 * * 1-5
      end: 0 17 * * 1-5
      desiredReplicas: "3"
  
  # Nocne przetwarzanie raportów (codziennie)
  - type: cron
    metadata:
      timezone: Europe/Warsaw
      start: 0 1 * * *      # Każdego dnia o 01:00
      end: 0 6 * * *        # Każdego dnia o 06:00
      desiredReplicas: "5"
  
  # Backupy w weekendy
  - type: cron
    metadata:
      timezone: Europe/Warsaw
      start: 0 2 * * 0      # Niedziela 02:00
      end: 0 8 * * 0        # Niedziela 08:00
      desiredReplicas: "4"
  
  # Miesięczne raporty - pierwszy dzień miesiąca
  - type: cron
    metadata:
      timezone: Europe/Warsaw
      start: 0 0 1 * *      # 1. dzień miesiąca o 00:00
      end: 0 12 1 * *       # 1. dzień miesiąca o 12:00
      desiredReplicas: "10"
  
  # Peak hour (lunch time) - dodatkowa moc
  - type: cron
    metadata:
      timezone: Europe/Warsaw
      start: 0 12 * * 1-5   # Pon-Pt 12:00
      end: 0 14 * * 1-5     # Pon-Pt 14:00
      desiredReplicas: "8"
  
  # UWAGA: Gdy wiele okien się nakłada, KEDA wybiera NAJWIĘKSZĄ wartość desiredReplicas

