apiVersion: v1
kind: Pod
metadata:
  name: nginx-failed
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginxx:latest
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi