apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reg-test
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - name: nginx
              protocol: TCP
              containerPort: 80