apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-resources
  labels:
    app: nginx-resources
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-resources
  template:
    metadata:
      labels:
        app: nginx-resources
    spec:
      containers:
      - name: nginx-resources
        image: nginx:1.25.1
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"