apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app-custom
  template:
    metadata:
      labels:
        app: example-app-custom
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - containerPort: 80
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        # W rzeczywistym scenariuszu należałoby dodać eksporter metryk
        # Ten przykład jest uproszczony dla celów demonstracyjnych 