elasticsearchHosts: "http://elasticsearch-master:9200"
kibanaConfig:
  kibana.yml: |
    elasticsearch.hosts: ["http://elasticsearch-master:9200"]
    xpack.security.enabled: false
    server.host: "0.0.0.0"
    server.publicBaseUrl: "http://localhost:5601"

service:
  type: ClusterIP
  port: 5601

replicaCount: 1 