apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todos-dawid
spec:
  ingressClassName: nginx
  rules:
  - host: dawidapp.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-clusterip
            port:
              number: 88