apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: azurecr
      containers:
      - name: web
        image: dawidsages.azurecr.io/maciej-todos-api:latest
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api
            port: 3001
          initialDelaySeconds: 20
          periodSeconds: 5
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-uri
      