apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: external-registry
      containers:
      - name: api
        image: dawid.azurecr.io/todos-be
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo-sts:27017/todos?authSource=admin"