apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
spec:
  schedule: "0/1 * * * *"  # co minutę
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          containers:
          - name: mongo-backup
            image: mongo:latest
            command:
              - /bin/sh
              - -c
              - |
                mongodump --uri="mongodb://root:password@mongo-service:27017/todos?authSource=admin" --out=/backup/$(date +%Y%m%d_%H%M%S)
            volumeMounts:
              - name: backup-volume
                mountPath: /backup
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: mongo-backup-pvc
          restartPolicy: Never
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi