# ResourceQuota definiuje limity zasobów dla całego namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources 
spec:
  hard:  # Sekcja 'hard' definiuje sztywne limity, których nie można przekroczyć
    # Limity zasobów obliczeniowych
    # requests.cpu: "4"        # Maksymalna suma requestów CPU dla wszystkich podów (4 rdzenie)
    # requests.memory: 4Gi     # Maksymalna suma requestów pamięci dla wszystkich podów (4 GB)
    # limits.cpu: "8"          # Maksymalna suma limitów CPU dla wszystkich podów (8 rdzeni)
    # limits.memory: 8Gi       # Maksymalna suma limitów pamięci dla wszystkich podów (8 GB)
    
    # Limity liczby obiektów
    pods: "15"               # Maksymalna liczba podów w namespace
    
    # Limity dla serwisów
    services: "5"            # Maksymalna liczba serwisów w namespace
    services.loadbalancers: "1"  # Maksymalna liczba serwisów typu LoadBalancer
    