# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-user-access
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: my-user
  namespace: kube-system
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io