# Nazwa i wersja chartu
apiVersion: v2
name: example-app
description: Przykładowy chart Helm dla aplikacji
type: application
version: 0.1.0
appVersion: "1.0.0"

# Zależności od innych chartów
dependencies:
  - name: prometheus
    version: "15.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled 