apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "55006bcd-0169-480f-a7e1-6b4ea7da3f63"
    keyvaultName: "kv-aks-demo-1761282322"
    tenantId: "14820cf7-d54a-4d85-9d98-1825fc5bebd6"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectAlias: DB_PASSWORD
        - |
          objectName: api-key
          objectType: secret
          objectAlias: API_KEY
        - |
          objectName: connection-string
          objectType: secret
          objectAlias: CONNECTION_STRING
  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: DB_PASSWORD
      key: db-password
    - objectName: API_KEY
      key: api-key
    - objectName: CONNECTION_STRING
      key: connection-string
