apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
      - name: azurecr
      containers:
      - name: web
        image: dawidsages.azurecr.io/cezary-web:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "1m"
          limits:
            memory: "1000Mi"
            cpu: "100m"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 20
        #   periodSeconds: 5
        env:
        - name: REACT_APP_API_URL
          value: "http://4.245.172.254:3001/api"