apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: my-app-with-metrics
  minReplicaCount: 1      # Minimum 1 replika
  maxReplicaCount: 10
  pollingInterval: 15     # Sprawdzaj co 15 sekund
  cooldownPeriod: 300     # 5 minut cooldown
  triggers:
  - type: prometheus
    metadata:
      # Adres Prometheus API
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
      
      # Nazwa metryki (dla HPA)
      metricName: http_requests_per_second
      
      # PromQL query - HTTP requests per second
      query: |
        sum(rate(http_request_duration_seconds_count{app="my-app-with-metrics"}[1m]))
      
      # Threshold - jedna replika na 50 req/s
      threshold: "50"
      
      # Ignoruj wartości null (gdy brak metryk)
      ignoreNullValues: "true"

