version: '3.8'

services:
  webapp:
    image: nginx:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "88:80"
    networks:
      - frontend

  api:
    image: nginx:latest
    deploy:
      replicas: 5
      # placement:
      #   constraints:
      #     - node.role == Leader
    networks:
      - frontend
      - backend
    # secrets:
    #   - api_key
    environment:
      - DB_HOST=db

  # db:
  #   image: postgres:13
  #   deploy:
  #     replicas: 1
  #     # placement:
  #     #   constraints:
  #     #     - node.labels.role == database
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   networks:
  #     - backend

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay
    # internal: true

volumes:
  db-data:

# secrets:
#   api_key:
#     # external: true