apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system # Często DaemonSety systemowe są umieszczane w kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      # Tolerancje są często potrzebne, aby DaemonSet mógł działać na węzłach master/control-plane
      # jeśli jest to wymagane. Poniższa tolerancja pozwala na uruchomienie na węzłach master.
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master # Starsza etykieta dla master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset # Przykładowy obraz
        # W rzeczywistym scenariuszu, tutaj byłaby konfiguracja Fluentd,
        # często poprzez ConfigMap i montowanie woluminów.
        env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-logging.kube-system.svc.cluster.local" # Przykład
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "9200" # Przykład
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers 