apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      restartPolicy: Never
      containers:
      - name: producer
        image: confluentinc/cp-kafka:7.5.0
        command:
        - sh
        - -c
        - |
          echo "Czekam na Kafka..."
          sleep 10
          
          echo "Tworzę topic (jeśli nie istnieje)..."
          kafka-topics --bootstrap-server kafka.default.svc.cluster.local:9092 \
            --create --if-not-exists \
            --topic test-topic \
            --partitions 3 \
            --replication-factor 1 || true
          
          echo "Produkuję 300 wiadomości..."
          for i in $(seq 1 300); do
            echo "Message number $i - $(date)" | \
              kafka-console-producer \
                --bootstrap-server kafka.default.svc.cluster.local:9092 \
                --topic test-topic
            
            # Wyświetl progress co 50 wiadomości
            if [ $((i % 50)) -eq 0 ]; then
              echo "Wyprodukowano $i wiadomości..."
            fi
            
            # Małe opóźnienie dla symulacji realnego trafficu
            sleep 0.1
          done
          
          echo "Zakończono! Wyprodukowano 300 wiadomości."
          
          # Wyświetl status topicu
          kafka-topics --bootstrap-server kafka.default.svc.cluster.local:9092 \
            --describe --topic test-topic
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

