apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-partition-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: kafka-consumer
  minReplicaCount: 0
  maxReplicaCount: 3          # Max 3 repliki (dla 3 partycji)
  pollingInterval: 15
  cooldownPeriod: 300
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.default.svc.cluster.local:9092
      consumerGroup: my-consumer-group
      topic: test-topic
      lagThreshold: "10"                   # Niski threshold
      activationLagThreshold: "5"
      limitToPartitionsWithLag: "true"     # Tylko partycje z lag
      
  # Ta konfiguracja będzie tworzyć do 3 replik (max liczba partycji)
  # Każda replika będzie konsumować z innych partycji

