apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-metrics
  namespace: default
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx-prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      app.kubernetes.io/instance: nginx-prom
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/instance: nginx-prom
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: metrics-stub
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:1.3.0
        args:
        - '-nginx.scrape-uri=http://127.0.0.1:8080/stub_status'
        ports:
        - containerPort: 9113
          name: metrics
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        server {
            listen 80;
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
        
        server {
            listen 8080;
            location /stub_status {
                stub_status on;
                access_log off;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx-prom
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 9113
    targetPort: 9113
    name: metrics
  selector:
    app: nginx
    app.kubernetes.io/instance: nginx-prom

