{{- if and .Values.mongodbSecret.create .Values.mongodbSecret.mongodbUri }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodbSecret.name }}
  labels:
    {{- include "todos-be-dawid.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ .Values.mongodbSecret.mongodbUri | b64enc }}
{{- end }}
