apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/os-sku-requested
                operator: In
                values:
                - Ubuntu
      containers:
      - name: nginx
        image: nginx:latest