# Upgrade Loki do wersji 3.5.7 z volume_enabled
# Chart: grafana/loki 6.44.0

# Tryb wdrożenia - SingleBinary dla prostoty (jak obecny loki-stack)
deploymentMode: SingleBinary

loki:
  # Konfiguracja Loki
  auth_enabled: false
  
  # Schemat storage - zgodny z obecną konfiguracją
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  
  # Storage lokalny (filesystem)
  storage:
    type: 'filesystem'
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  
  # WŁĄCZENIE volume_enabled
  limits_config:
    max_entries_limit_per_query: 5000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    volume_enabled: true  # <-- To jest kluczowe!
  
  # Persistence dla danych
  storage_config:
    filesystem:
      directory: /var/loki/chunks

# SingleBinary deployment
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 256Mi

# Backend - wyłączony w SingleBinary
backend:
  replicas: 0

# Read - wyłączony w SingleBinary
read:
  replicas: 0

# Write - wyłączony w SingleBinary
write:
  replicas: 0

# Gateway
gateway:
  enabled: false

# Monitoring
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

# Test
test:
  enabled: false

# Promtail - musi być zainstalowany osobno lub użyć obecnego
# Obecny promtail z loki-stack będzie działać z nowym Loki

