apiVersion: v1
kind: Service
metadata:
  name: example-app-custom
spec:
  selector:
    app: example-app-custom
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 8080
    targetPort: 8080
    name: metrics
  type: ClusterIP 