# Konfiguracja datasources dla Grafana
# Aplikuj po instalacji: kubectl apply -f grafana-datasources.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-stack-kube-prom-prometheus:9090
        uid: prometheus
        isDefault: true
        jsonData:
          timeInterval: "30s"
      
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        uid: loki
        jsonData:
          maxLines: 1000
      
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        uid: tempo
        jsonData:
          httpMethod: GET
          nodeGraph:
            enabled: true
          search:
            hide: false

