kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# ── Węzły ───────────────────────────────────────────────
nodes:
- role: control-plane
  image: kindest/node:v1.31.0        # wersja K8s
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:                 # host → klaster
  - containerPort: 80
    hostPort: 8088
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  - containerPort: 30002
    hostPort: 30002
    protocol: TCP
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
  - hostPath: /tmp/kind-data
    containerPath: /mnt/data
- role: worker
  extraMounts:
  - hostPath: /tmp/kind-data
    containerPath: /mnt/data
- role: worker
  extraMounts:
  - hostPath: /tmp/kind-data
    containerPath: /mnt/data

# Konfiguracja CNI
networking:
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"

# Konfiguracja dla PersistentVolumes
containerdConfigPatches:
- |
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
      SystemdCgroup = true