kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# ── Węzły ───────────────────────────────────────────────
nodes:
- role: control-plane
  image: kindest/node:v1.31.0        # wersja K8s
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:                 # host → klaster
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
- role: worker
- role: worker

# ── (opcjonalnie) wolumen współdzielony ──────────
# extraMounts:
# - hostPath: /home/$USER/lab-data
#   containerPath: /mnt/data