# Określa wersję składni Docker Compose, której używamy w tym pliku.
# Wersja 3.8 wprowadza najnowsze funkcje i jest kompatybilna z Docker Engine w wersji 19.03.0+.
# Wybór tej wersji pozwala na korzystanie z zaawansowanych opcji konfiguracyjnych.
version: '3.8'

# Pola dostępne w wersji 3.8 obejmują:
# - services: definiuje usługi (kontenery) w aplikacji
# - networks: określa sieci używane przez usługi
# - volumes: definiuje trwałe woluminy dla usług
# - configs: zarządza konfiguracjami dla usług
# - secrets: zarządza poufnymi danymi dla usług
# - deploy: określa konfigurację wdrożenia dla usług (głównie dla trybu swarm)

services:
  nginx:
    image: nginx:latest
    container_name: moj-nginx-kontener
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - nginx_logs:/var/log/nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  frontend:
    driver: bridge

volumes:
  nginx_logs:
    driver: local

