   apiVersion: networking.k8s.io/v1
   kind: NetworkPolicy
   metadata:
     name: isolate-namespace
   spec:
     podSelector: {}
     policyTypes:
     - Ingress
     ingress:
     - from:
       - podSelector: {}  # Pozwala na komunikację między Podami w tym samym namespace
       - namespaceSelector:
           matchLabels:
             name: prod   # Pozwala na komunikację z namespace prod