# token-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aks-admin-sa-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: aks-admin-sa
type: kubernetes.io/service-account-token