kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dawid
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["mongodb-secret"]
  verbs: ["get"]