apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-producer
spec:
  template:
    metadata:
      labels:
        app: rabbitmq-producer
    spec:
      restartPolicy: Never
      containers:
      - name: producer
        image: ghcr.io/kedacore/tests-rabbitmq:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq.default.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: QUEUE_NAME
          value: "test-queue"
        - name: MESSAGE_COUNT
          value: "100"      # Wyprodukuj 100 wiadomości
        - name: CONSUME
          value: "false"    # Tylko produkuj, nie konsumuj
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

