apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx-sts
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None # Kluczowe dla Headless Service
  selector:
    app: nginx-sts # Musi pasować do etykiet Podów StatefulSet 