apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-temp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-temp
  template:
    metadata:
      labels:
        app: api-temp
    spec:
      imagePullSecrets:
      - name: external-registry
      containers:
      - name: api
        image: dawid.azurecr.io/todo-be-rh3:1.0
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: "mongodb://root:password@todos-mongo-mongodb:27017/todos?authSource=admin"