apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: external-registry
      containers:
      - name: api
        image: dawid.azurecr.io/todos-be
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/todos?replicaSet=rs0&authSource=admin"