apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx-headless" # Nazwa Headless Service
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sts # Musi pasować do etykiet w szablonie Poda i selektorze Headless Service
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  # Definicja szablonu PersistentVolumeClaim (opcjonalna, ale typowa dla StatefulSet)
  # W tym prostym przykładzie bez PV, Pody nie będą miały trwałego przechowywania danych.
  # Aby dodać trwałe przechowywanie, odkomentuj i dostosuj poniższą sekcję:
  volumeClaimTemplates:
  - metadata:
      name: www # Nazwa PVC, np. www-web-0, www-web-1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard" # Użyj odpowiedniej StorageClass dla Twojego klastra
      resources:
        requests:
          storage: 1Gi 